version: "3.7"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment: 
      - POSTGRES_PASSWORD=27603e12416d8d5af5862e3ed4ce890d
      - POSTGRES_USER=methylation
      - POSTGRES_DB=methylation
    ports:
      - "5432:5432"
    networks:
      - webapp
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/log:/var/log/postgresql
  shinyproxy:
    image: adoptopenjdk:8-jre-openj9
    container_name: shinyproxy
    ports:
      - "8080:8080"
    networks:
      - webapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy:/opt/shinyproxy
    working_dir: /opt/shinyproxy
    command: java -jar shinyproxy-2.3.0.jar

networks:
  webapp:
    name: webapp
