version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment: # make this an env file
      - POSTGRES_PASSWORD=27603e12416d8d5af5862e3ed4ce890d
      - POSTGRES_USER=methylation
      - POSTGRES_DB=methylation
    ports:
      - "5432:5432"
    networks:
      - webapp
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/log:/var/log/postgresql
    restart: unless-stopped

  pipeline:
    image: pipeline:latest
    networks:
      - webapp
    depends_on:
      - postgres
    volumes:
      - ./:/opt/app
    restart: unless-stopped

  shinyproxy:
    build: shinyproxy
    image: methylation-shinyproxy
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - webapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  webapp:
    name: webapp
