version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - main
    restart: unless-stopped
  executor:
    build:
      context: analysis
      args:
        BIOCONDUCTOR_VERSION: "${BIOCONDUCTOR_VERSION}"
    image: methylation-executor
    depends_on:
      - postgres
    networks:
      - main
    volumes:
      - ./analysis/logs:/opt/app/logs
      - uploads:/opt/app/files
    restart: unless-stopped
  shinyproxy:
    build:
      context: shinyproxy
      args:
        JDK_VERSION: "${JDK_VERSION}"
        SHINYPROXY_VERSION: "${SHINYPROXY_VERSION}"
    image: "methylation-shinyproxy:${SHINYPROXY_VERSION}_${JDK_VERSION}"
    depends_on:
      - postgres
    ports:
      - "${SHINYPROXY_HOST_PORT}:8080"
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./shinyproxy/logs:/opt/shinyproxy/logs
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    depends_on:
      - shinyproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
#     - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
networks:
  main:
    name: methylation-main
volumes:
  uploads:
    name: methylation-uploads
