version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
      - ./db/log:/var/log/postgresql
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - main
    restart: unless-stopped

  pipeline:
    image: pipeline:latest
    networks:
      - main
    depends_on:
      - postgres
    volumes:
      - ./:/opt/app
    restart: unless-stopped

  shinyproxy:
    build:
      context: shinyproxy
      args:
        JDK_VERSION: "${JDK_VERSION}"
        SHINYPROXY_VERSION: "${SHINYPROXY_VERSION}"
    image: "methylation-shinyproxy:${SHINYPROXY_VERSION}_${JDK_VERSION}"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  main:
    name: methylation-main
