version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - main
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped

  executor:
    build:
      context: analysis
      args:
        R_VERSION: "${R_VERSION}"
    image: ghcr.io/kevinlul/methylation-executor
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    networks:
      - main
    volumes:
      #- ./analysis/externaldata:/opt/app/externaldata
      #- ./analysis/extrasample:/opt/app/extrasample
      - ./analysis/logs:/opt/app/logs
      - ./files:/opt/app/files
    restart: unless-stopped

  shiny-build:
    build:
      context: app
      args:
        R_VERSION: "${R_VERSION}"
    image: ghcr.io/kevinlul/methylation-shiny
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: echo
    networks:
      - main
    volumes:
      - ./files:/opt/app/files
    restart: "no"

  shinyproxy:
    build:
      context: shinyproxy
      args:
        JDK_VERSION: "${JDK_VERSION}"
        SHINYPROXY_VERSION: "${SHINYPROXY_VERSION}"
    image: "ghcr.io/kevinlul/methylation-shinyproxy:${SHINYPROXY_VERSION}_${JDK_VERSION}"
    environment:
      SHINY_UPLOAD_VOLUME: "${PWD}/files"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
      - shiny-build
    ports:
      - "${SHINYPROXY_HOST_PORT}:8080"
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./shinyproxy/logs:/opt/shinyproxy/logs
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - shinyproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped

networks:
  main:
    name: methylation-main
