version: "3.8"

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    networks:
      - main
    restart: unless-stopped

  executor:
    build: analysis
    image: methylation-executor
    depends_on:
      - postgres
    networks:
      - main
    volumes:
      - ./analysis/externaldata:/opt/app/externaldata
      - ./analysis/extrasample:/opt/app/extrasample
      - ./analysis/logs:/opt/app/logs
      - "./files:/opt/app/files"
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_PORT: "${POSTGRES_HOST_PORT}"
      POSTGRES_HOST: postgres

  shiny-build:
    build: app
    image: methylation-shiny
    command: echo
    volumes:
      - "./files:/opt/app/files"
    networks:
      - main
    restart: "no"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_PORT: "${POSTGRES_HOST_PORT}"
      POSTGRES_HOST: postgres

  shinyproxy:
    build:
      context: shinyproxy
      args:
        JDK_VERSION: "${JDK_VERSION}"
        SHINYPROXY_VERSION: "${SHINYPROXY_VERSION}"
    image: "methylation-shinyproxy:${SHINYPROXY_VERSION}_${JDK_VERSION}"
    environment:
      SHINY_UPLOAD_VOLUME: "${PWD}/files"
    depends_on:
      - postgres
    #  - shiny-build
    ports:
      - "${SHINYPROXY_HOST_PORT}:8080"
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./shinyproxy/logs:/opt/shinyproxy/logs
    restart: unless-stopped

  #nginx:
  #  image: nginx:alpine
  #  depends_on:
  #    - shinyproxy
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  networks:
  #    - main
  #  volumes:
  #    - ./nginx/conf.d:/etc/nginx/conf.d
  #    - ./nginx/certs:/etc/nginx/certs
#     - ./nginx/logs:/var/log/nginx
  #  restart: unless-stopped
networks:
  main:
    name: methylation-main
