proxy:
  title: METHYLATION APP
  landing-page: /app/webapp
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  hide-navbar: true
  specs:
  - id: webapp
    display-name: Methylation Webapp
    description: Shiny web application for Zadeh lab
    container-cmd: ["R", "-e", "shiny::runApp(appDir='/opt/app/app')"]
    container-image: app:latest
    container-network: webapp
    container-volumes: ["/home/alper/Documents/webapp/meningioma:/opt/app"]

logging:
  file:
    shinyproxy.log
