proxy:
  title: METHYLATION APP
  landing-page: /app_direct/webapp
  heartbeat-rate: 10000
  heartbeat-timeout: 1800000
  port: 8080
  authentication: none
  hide-navbar: true
  docker:
    internal-networking: true
  container-log-path: logs
  specs:
  - id: webapp
    display-name: Methylation Webapp
    description: Shiny web application for Zadeh lab
    container-image: ghcr.io/kevinlul/methylation-shiny:latest
    container-env:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
    container-network: methylation-main
    container-volumes: ["${SHINY_UPLOAD_VOLUME}:/opt/app/files"]
logging:
  file:
    logs/shinyproxy.log
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
