# this is the config file for the app
# if you are adding this to your git repo
# DO NOT fill in the username and password
# instead create a backup and add that to your git
# and the filled file to your .gitignore

basepath: ""
sample_files: files/
encryption:
  algorithm: sha512 #lowercase these are function names in R
email:
  address: admin@email.com  #these are just for notifications I will not send emails
app_files:
  appdir:
  modules:
    login: modules/login.R
    admin: modules/admin.R
    user: modules/user.R
    account_settings: modules/account_settings.R
    upload_sample: modules/upload_sample.R
