version: "3.8"

services:
  shiny:
    build: .
    image: methylation-shiny
    ports:
      - "3838:3838"
    volumes:
      - uploads:/opt/app/files
    #  - .:/opt/app
    networks:
      - main
networks:
  main:
    name: methylation-main
volumes:
  uploads:
    name: methylation-uploads
