version: "3.8"

services:
  shiny:
    build: .
    image: methylation-shiny
    ports:
      - "3838:3838"
    volumes:
      - "../files:/opt/app/files"
    #  - .:/opt/app
    networks:
      - main
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_PORT: "${POSTGRES_HOST_PORT}"
      POSTGRES_HOST: postgres
      
networks:
  main:
    name: methylation-main
