version: "3.8"

services:
  shiny:
    image: methylation-shiny
    build: .
    ports:
      - "3838:3838"
    user: shiny
    # volumes:
    #  - .:/srv/shiny-server
    #  - ./log:/var/log/shiny-server
    networks:
      - main

networks:
  main:
    name: methylation-main
