version: "3.8"

services:
  shiny:
    build: .
    image: methylation-shiny
    ports:
      - "3838:3838"
    user: shiny
    volumes:
      - uploads:/srv/shiny-server/files
    #  - .:/srv/shiny-server
    networks:
      - main
networks:
  main:
    name: methylation-main
volumes:
  uploads:
    name: methylation-uploads
