# this is the config file for the app
# if you are adding this to your git repo
# DO NOT fill in the username and password
# instead create a backup and add that to your git
# and the filled file to your .gitignore

basepath: "./"
sample_files: files/
analysis:
  pipeline: analysis_pipeline.R
  rmd: sample_report.Rmd
  logs: logs
  extrasample: extrasample
  externaldata: externaldata


